name: Run tests

on:
  push:
    branches:
      - '*'  # Run on every branch push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8' # Use Java 8

      - name: Build with Maven
        run: |
          mvn -B clean verify
          mvn -Dtest=mcapi.davidout.* test
